class Q < Formula
  desc "CLI tool for querying LLMs"
  homepage "https://github.com/rfushimi/q"
  # The URL and SHA256 will be automatically available after pushing a tag
  # The SHA256 can be found in the release assets as q-v0.1.0.tar.gz.sha256
  # Or by running: curl -L https://github.com/rfushimi/q/releases/download/v0.1.0/q-v0.1.0.tar.gz.sha256
  url "https://github.com/rfushimi/q/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256" # Will be generated by GitHub Actions
  version "0.1.0"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--root", prefix, "--path", "."
  end

  test do
    assert_match "q #{version}", shell_output("#{bin}/q --version")
  end
end
